info_text = ("<h2>Help</h2>"
        "<big>1. Choose your target folder to process images.<br>"
        "2. Choose your watermark to apply.<br>"
        "3. Set desired settings.<br>"
        "4. Click \"❇️ Mark it!\".<br><br>"
        "Supported image types: PNG, JPG, JPEG.<br>"
        "Offsets set from top-left corner.</big>"
        "<hr><h2>Pix Watermark v1.0.1</h2>"
        "<big>Check the source code: <a href='https://github.com/cauchemarno/PixWatermark'>GitHub</a>.<br>"
        "App logo is an emoji graphics from <a href='https://github.com/twitter/twemoji'>Twemoji</a> by Twitter(X), "
        "used under <a href='https://creativecommons.org/licenses/by/4.0/'>CC BY 4.0</a>.</big>")